--1
Select AUDITORIUM.AUDITORIUM,AUDITORIUM_TYPE.AUDITORIUM_TYPENAME
From AUDITORIUM_TYPE
inner join AUDITORIUM
on AUDITORIUM.AUDITORIUM_TYPE = AUDITORIUM_TYPE.AUDITORIUM_TYPE
--2
Select AUDITORIUM.AUDITORIUM,AUDITORIUM_TYPE.AUDITORIUM_TYPENAME
From AUDITORIUM_TYPE
inner join AUDITORIUM
on AUDITORIUM.AUDITORIUM_TYPE = AUDITORIUM_TYPE.AUDITORIUM_TYPE and
									AUDITORIUM_TYPE.AUDITORIUM_TYPENAME like '%компьютер%'
--3
Select AUDITORIUM.AUDITORIUM,AUDITORIUM_TYPE.AUDITORIUM_TYPENAME--1
From AUDITORIUM_TYPE,AUDITORIUM
Where AUDITORIUM.AUDITORIUM_TYPE = AUDITORIUM_TYPE.AUDITORIUM_TYPE

Select AUDITORIUM.AUDITORIUM,AUDITORIUM_TYPE.AUDITORIUM_TYPENAME--2
From AUDITORIUM_TYPE,AUDITORIUM
Where AUDITORIUM.AUDITORIUM_TYPE = AUDITORIUM_TYPE.AUDITORIUM_TYPE And
									AUDITORIUM_TYPE.AUDITORIUM_TYPENAME Like '%компьютер%'
--4
select PROGRESS.NOTE[Оценка], STUDENT.NAME[Имя студента], SUBJECT.SUBJECT[Дисциплина],
PULPIT.PULPIT[Кафедра], FACULTY.FACULTY[Факультет], 
GROUPS.PROFESSION[Специальность],

case
when (PROGRESS.NOTE = 6) then 'шесть'
when (PROGRESS.NOTE = 7) then 'семь'
when (PROGRESS.NOTE = 8) then 'восемь'
else 'не между 6 и 8'
end [Примечание]
from FACULTY 
INNER JOIN PULPIT
on FACULTY.FACULTY = PULPIT.FACULTY
INNER JOIN GROUPS
on FACULTY.FACULTY = GROUPS.FACULTY
INNER JOIN SUBJECT
on PULPIT.PULPIT = SUBJECT.PULPIT
INNER JOIN STUDENT
on STUDENT.IDGROUP = GROUPS.IDGROUP
INNER JOIN PROGRESS
on PROGRESS.IDSTUDENT = STUDENT.IDSTUDENT
where PROGRESS.NOTE between 6 and 8
order by PROGRESS.NOTE desc;
--5
select PROGRESS.NOTE[Оценка], STUDENT.NAME[Имя студента], SUBJECT.SUBJECT[Дисциплина],
PULPIT.PULPIT[Кафедра], FACULTY.FACULTY[Факультет], 
GROUPS.PROFESSION[Специальность],

case
when (PROGRESS.NOTE = 6) then 'шесть'
when (PROGRESS.NOTE = 7) then 'семь'
when (PROGRESS.NOTE = 8) then 'восемь'
else 'не между 6 и 8'
end [Примечание]
from FACULTY 
INNER JOIN PULPIT
on FACULTY.FACULTY = PULPIT.FACULTY
INNER JOIN GROUPS
on FACULTY.FACULTY = GROUPS.FACULTY
INNER JOIN SUBJECT
on PULPIT.PULPIT = SUBJECT.PULPIT
INNER JOIN STUDENT
on STUDENT.IDGROUP = GROUPS.IDGROUP
INNER JOIN PROGRESS
on PROGRESS.IDSTUDENT = STUDENT.IDSTUDENT
where PROGRESS.NOTE between 6 and 8
order by
(
	case 
		when (PROGRESS.NOTE = 6) then 3
		when (PROGRESS.NOTE = 7) then 1
		when (PROGRESS.NOTE = 8) then 2
	end 
)

--6
Select PULPIT.PULPIT_NAME, isnull(TEACHER.TEACHER_NAME,'***')[Учителя]
from PULPIT Left Outer Join TEACHER
on PULPIT.PULPIT = TEACHER.PULPIT
union 
Select isnull(PULPIT.PULPIT_NAME,'***'), TEACHER.TEACHER_NAME
from PULPIT Right Outer Join TEACHER
on PULPIT.PULPIT = TEACHER.PULPIT
--8
select isnull(PULPIT.PULPIT_NAME, '***') PULPIT, isnull(TEACHER.TEACHER_NAME, '***') TEACHER 
FROM TEACHER full outer join PULPIT
ON PULPIT.PULPIT = TEACHER.PULPIT;

select isnull(PULPIT.PULPIT_NAME, '***') PULPIT, isnull(TEACHER.TEACHER_NAME, '***') TEACHER 
FROM PULPIT full outer join TEACHER
ON PULPIT.PULPIT = TEACHER.PULPIT;

select isnull(PULPIT.PULPIT_NAME, '***') PULPIT, isnull(TEACHER.TEACHER_NAME, '***') TEACHER 
FROM PULPIT INNER join TEACHER
ON PULPIT.PULPIT = TEACHER.PULPIT;

select TEACHER.TEACHER_NAME, PULPIT.PULPIT
FROM TEACHER full outer join PULPIT
ON PULPIT.PULPIT = TEACHER.PULPIT
where PULPIT.PULPIT is null;

select TEACHER.TEACHER_NAME, PULPIT.PULPIT
FROM PULPIT full outer join TEACHER
ON PULPIT.PULPIT = TEACHER.PULPIT
where TEACHER is null;

select PULPIT.PULPIT, TEACHER.TEACHER_NAME
FROM TEACHER full outer join PULPIT
ON PULPIT.PULPIT = TEACHER.PULPIT
where TEACHER.TEACHER_NAME is not null;

--9
select AUDITORIUM.AUDITORIUM, AUDITORIUM_TYPE.AUDITORIUM_TYPENAME
from AUDITORIUM cross join AUDITORIUM_TYPE
where AUDITORIUM.AUDITORIUM_TYPE = AUDITORIUM_TYPE.AUDITORIUM_TYPE;

