use UNIVER;
select GROUPS.PROFESSION, PROGRESS.SUBJECT,GROUPS.FACULTY,
 round(avg(cast(PROGRESS.NOTE as float(4))),2)[Средняя оценка]
	from GROUPS join FACULTY
		on GROUPS.FACULTY = FACULTY.FACULTY
			join STUDENT
				on STUDENT.IDGROUP = GROUPS.IDGROUP
					join PROGRESS
						on PROGRESS.IDSTUDENT = STUDENT.IDSTUDENT
	where GROUPS.FACULTY like 'ТОВ'
group by GROUPS.PROFESSION,PROGRESS.SUBJECT,GROUPS.FACULTY
--1.1
select GROUPS.PROFESSION, PROGRESS.SUBJECT,GROUPS.FACULTY,
 round(avg(cast(PROGRESS.NOTE as float(4))),2)[Средняя оценка]
	from GROUPS join FACULTY
		on GROUPS.FACULTY = FACULTY.FACULTY
			join STUDENT
				on STUDENT.IDGROUP = GROUPS.IDGROUP
					join PROGRESS
						on PROGRESS.IDSTUDENT = STUDENT.IDSTUDENT
	where GROUPS.FACULTY like 'ТОВ'
group by rollup (GROUPS.PROFESSION,PROGRESS.SUBJECT,GROUPS.FACULTY)
--2
select GROUPS.PROFESSION, PROGRESS.SUBJECT,GROUPS.FACULTY,
 round(avg(cast(PROGRESS.NOTE as float(4))),2)[Средняя оценка]
	from GROUPS join FACULTY
		on GROUPS.FACULTY = FACULTY.FACULTY
			join STUDENT
				on STUDENT.IDGROUP = GROUPS.IDGROUP
					join PROGRESS
						on PROGRESS.IDSTUDENT = STUDENT.IDSTUDENT
	where GROUPS.FACULTY like 'ТОВ'
group by cube (GROUPS.PROFESSION,PROGRESS.SUBJECT,GROUPS.FACULTY)
--3
select GROUPS.PROFESSION, PROGRESS.SUBJECT,GROUPS.FACULTY,
 round(avg(cast(PROGRESS.NOTE as float(4))),2)[Средняя оценка]
	from GROUPS join FACULTY
		on GROUPS.FACULTY = FACULTY.FACULTY
			join STUDENT
				on STUDENT.IDGROUP = GROUPS.IDGROUP
					join PROGRESS
						on PROGRESS.IDSTUDENT = STUDENT.IDSTUDENT
	where GROUPS.FACULTY like 'ТОВ'
group by GROUPS.PROFESSION,PROGRESS.SUBJECT,GROUPS.FACULTY
union all
select GROUPS.PROFESSION, PROGRESS.SUBJECT,GROUPS.FACULTY,
 round(avg(cast(PROGRESS.NOTE as float(4))),2)[Средняя оценка]
	from GROUPS join FACULTY
		on GROUPS.FACULTY = FACULTY.FACULTY
			join STUDENT
				on STUDENT.IDGROUP = GROUPS.IDGROUP
					join PROGRESS
						on PROGRESS.IDSTUDENT = STUDENT.IDSTUDENT
	where GROUPS.FACULTY like 'ХТиТ'
group by GROUPS.PROFESSION,PROGRESS.SUBJECT,GROUPS.FACULTY
--4
select GROUPS.PROFESSION, PROGRESS.SUBJECT,GROUPS.FACULTY,
 round(avg(cast(PROGRESS.NOTE as float(4))),2)[Средняя оценка]
	from GROUPS join FACULTY
		on GROUPS.FACULTY = FACULTY.FACULTY
			join STUDENT
				on STUDENT.IDGROUP = GROUPS.IDGROUP
					join PROGRESS
						on PROGRESS.IDSTUDENT = STUDENT.IDSTUDENT
	where GROUPS.FACULTY like 'ТОВ'
group by GROUPS.PROFESSION,PROGRESS.SUBJECT,GROUPS.FACULTY
intersect
select GROUPS.PROFESSION, PROGRESS.SUBJECT,GROUPS.FACULTY,
 round(avg(cast(PROGRESS.NOTE as float(4))),2)[Средняя оценка]
	from GROUPS join FACULTY
		on GROUPS.FACULTY = FACULTY.FACULTY
			join STUDENT
				on STUDENT.IDGROUP = GROUPS.IDGROUP
					join PROGRESS
						on PROGRESS.IDSTUDENT = STUDENT.IDSTUDENT
	where GROUPS.FACULTY like 'ХТиТ'
group by GROUPS.PROFESSION,PROGRESS.SUBJECT,GROUPS.FACULTY
--5
select GROUPS.PROFESSION, PROGRESS.SUBJECT,GROUPS.FACULTY,
 round(avg(cast(PROGRESS.NOTE as float(4))),2)[Средняя оценка]
	from GROUPS join FACULTY
		on GROUPS.FACULTY = FACULTY.FACULTY
			join STUDENT
				on STUDENT.IDGROUP = GROUPS.IDGROUP
					join PROGRESS
						on PROGRESS.IDSTUDENT = STUDENT.IDSTUDENT
	where GROUPS.FACULTY like 'ТОВ'
group by GROUPS.PROFESSION,PROGRESS.SUBJECT,GROUPS.FACULTY
except
select GROUPS.PROFESSION, PROGRESS.SUBJECT,GROUPS.FACULTY,
 round(avg(cast(PROGRESS.NOTE as float(4))),2)[Средняя оценка]
	from GROUPS join FACULTY
		on GROUPS.FACULTY = FACULTY.FACULTY
			join STUDENT
				on STUDENT.IDGROUP = GROUPS.IDGROUP
					join PROGRESS
						on PROGRESS.IDSTUDENT = STUDENT.IDSTUDENT
	where GROUPS.FACULTY like 'ХТиТ'
group by GROUPS.PROFESSION,PROGRESS.SUBJECT,GROUPS.FACULTY