use UNIVER;

select FACULTY.FACULTY,PULPIT.PULPIT_NAME,PROFESSION.PROFESSION_NAME
from FACULTY,PULPIT,PROFESSION
where PULPIT.FACULTY = FACULTY.FACULTY and FACULTY.FACULTY= PROFESSION.FACULTY
and PROFESSION.PROFESSION_NAME in (
select PROFESSION.PROFESSION_NAME
from PROFESSION
where(PROFESSION.PROFESSION_NAME like '%технология%'
or PROFESSION.PROFESSION_NAME like '%технологии%'));
--2
select FACULTY.FACULTY_NAME, PULPIT.PULPIT_NAME, PROFESSION.PROFESSION_NAME
from FACULTY join PULPIT
on PULPIT.FACULTY=FACULTY.FACULTY, PROFESSION
where PULPIT.FACULTY=FACULTY.FACULTY and FACULTY.FACULTY=PROFESSION.FACULTY
and
PROFESSION.PROFESSION_NAME in
(select PROFESSION.PROFESSION_NAME
from PROFESSION
where(PROFESSION.PROFESSION_NAME like '%технология%'
or PROFESSION.PROFESSION_NAME like '%технологии'));
--3
select FACULTY.FACULTY,PULPIT.PULPIT_NAME,PROFESSION.PROFESSION_NAME
from FACULTY join PULPIT
on PULPIT.FACULTY = FACULTY.FACULTY 
join PROFESSION
on PROFESSION.FACULTY = FACULTY.FACULTY
where(PROFESSION.PROFESSION_NAME like '%технология%'
or PROFESSION.PROFESSION_NAME like '%технологии%');
--4
select AUDITORIUM_CAPACITY, AUDITORIUM_TYPE
from AUDITORIUM  a
where AUDITORIUM_CAPACITY=(select top(1) aa.AUDITORIUM_CAPACITY from AUDITORIUM aa
where aa.AUDITORIUM_TYPE=a.AUDITORIUM_TYPE order by AUDITORIUM_CAPACITY desc);
--5
select FACULTY_NAME from FACULTY
where not exists (select* from PULPIT 
where FACULTY.FACULTY = PULPIT.FACULTY);
--6
select top 1
( select avg(NOTE) from PROGRESS
where PROGRESS.SUBJECT like 'БД')[бд],
(select avg(NOTE) from PROGRESS
where PROGRESS.SUBJECT like 'ОАиП')[оаип],
(select avg(NOTE) from PROGRESS
where PROGRESS.SUBJECT like 'СУБД')[субд]
from PROGRESS
--7
select IDSTUDENT,NOTE
from PROGRESS student1
where student1.NOTE >= all(select NOTE
from PROGRESS student2
where student1.IDSTUDENT != student2.IDSTUDENT);
--8
select IDSTUDENT, NOTE
from PROGRESS student1
where student1.NOTE >= ANY(select NOTE 
from PROGRESS student2
where student1.IDSTUDENT!=student2.IDSTUDENT);